apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tba-activemq
  name: tba-activemq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: tba-activemq
    spec:
      containers:
      - image: 10.98.74.120:5000/tba-activemq.5.15.1:1.0.1-SNAPSHOT
        name: tba-activemq
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        - containerPort: 61616
        - containerPort: 8161
        - containerPort: 5672
        - containerPort: 61613
        - containerPort: 1883
        - containerPort: 61614
        resources: {}
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/activemq/data
          subPath: tba/evergreen2/activemq/data
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      imagePullSecrets:
      - name: regsecret
status: {}
