apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tba-kylo-services
  name: tba-kylo-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tba-kylo-services
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: 10.98.74.120:5000/tba-kylo-services.8.4:1.0.0-SNAPSHOT
        name: tba-kylo-services
        imagePullPolicy: IfNotPresent
        #lifecycle:
          #postStart:
            #exec:
             #command: ["/bin/sh", "-c", "/opt/kylo/kylo-services/spark-shell/kylo-spark-shell-starter.sh"]
        ports:
        - containerPort: 8420
        - containerPort: 8450
        resources: {}
        volumeMounts:
        - mountPath: /opt/kylo/kylo-services/conf
          name: kylo-services-config
        - mountPath: /opt/kylo/kylo-services/spark-shell
          name: kylo-services-spark
        - name: glusterfsvol
          mountPath: /var/log/kylo-services
          subPath: tba/evergreen2/kylo-services/log
        - name: glusterfsvol
          mountPath: /etc/security/daf.keytab
          subPath: tba/security/daf.keytab
          readOnly: true
        - name: sparkhome
          mountPath: /opt/cloudera/parcels/
          readOnly: true
        - name: sparkconf
          mountPath: /etc/spark2/
          readOnly: true
        - name: alternatives
          mountPath: /etc/alternatives/
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
          readOnly: true
        - name: hadoop
          mountPath: /etc/hadoop
          readOnly: true
        - name: daf-root-ca
          mountPath: /etc/ssl/certs
      restartPolicy: Always
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim

      - name: kylo-services-config
        configMap:
          name: kylo-services
      - name: kylo-services-spark
        configMap:
          name: kylo-services-spark
      - name: kylo-auth-config
        configMap:
          name: kylo-auth-config
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoop
        hostPath:
          path: /etc/hadoop
      - name: sparkhome
        hostPath:
          path: /opt/cloudera/parcels/
      - name: alternatives
        hostPath:
          path: /etc/alternatives/
      - name: sparkconf
        hostPath:
          path: /etc/spark2/

      - name: daf-root-ca
        secret:
          secretName: daf-root-ca
      imagePullSecrets:
      - name: regsecret
status: {}
