apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tba-nifi
  name: tba-nifi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tba-nifi
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: 10.98.74.120:5000/tba-nifi.1.4.0:1.0.7-SNAPSHOT
        name: tba-nifi
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", " echo \"nameserver 10.96.0.10\n$(cat /etc/resolv.conf)\" > /etc/resolv.conf"]
        ports:
        - containerPort: 8080
        - containerPort: 8033 # To test basic templates inside nifi
        resources: {}
        volumeMounts:
        - name: glusterfsvol
          mountPath: /usr/nifi/data
          subPath: tba/evergreen2/nifi/data
          readOnly: false
        - name: glusterfsvol
          mountPath: /usr/nifi/logs
          subPath: tba/evergreen2/nifi/log
          readOnly: false
        - name: glusterfsvol
          mountPath: /tmp/kylo-nifi/failed-flows
          subPath: tba/evergreen2/nifi/failed-flows
          readOnly: false
        - name: sparkhome
          mountPath: /opt/cloudera/parcels/
          readOnly: true
        - name: sparkconf
          mountPath: /etc/spark2/
          readOnly: true
        - name: spark1conf
          mountPath: /etc/spark/
          readOnly: true
        - name: alternatives
          mountPath: /etc/alternatives/
          readOnly: true
        - name: glusterfsvol
          mountPath: /usr/nifi/daf.keytab
          subPath: tba/security/daf.keytab
          readOnly: true
        - name: glusterfsvol
          mountPath: /etc/security/
          subPath: tba/security/
          readOnly: true
        - name: nifi-config
          mountPath: /usr/nifi/conf
        - name: nifi-kylo
          mountPath: /usr/nifi/ext-config
        - name: hosts
          mountPath: /etc/extra_hosts
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
          readOnly: true
        - name: hadoop
          mountPath: /etc/hadoop
          readOnly: true
        - name: hive
          mountPath: /etc/hive
          readOnly: true
        - name: hbase
          mountPath: /etc/hbase
          readOnly: true
        - name: glusterfsvol
          mountPath: /usr/nifi/scripts
          subPath: nifi/scripts/edge1
          readOnly: true
        #- name: daf-root-ca
        #  mountPath: /etc/ssl/certs
        - name: home
          mountPath: /home
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: nifi-config
        configMap:
          name: nifi
      - name: nifi-kylo
        configMap:
          name: nifi-kylo
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoop
        hostPath:
          path: /etc/hadoop
      - name: sparkhome
        hostPath:
          path: /opt/cloudera/parcels/
      - name: alternatives
        hostPath:
          path: /etc/alternatives/
      - name: sparkconf
        hostPath:
          path: /etc/spark2/
      - name: spark1conf
        hostPath:
          path: /etc/spark/
      - name: hbase
        hostPath:
          path: /etc/hbase/
      - name: hive
        hostPath:
          path: /etc/hive/
      #- name: daf-root-ca
      #  secret:
      #    secretName: daf-root-ca
      - name: home
        hostPath:
          path: /home
      imagePullSecrets:
      - name: regsecret
      nodeSelector:
        kubernetes.io/hostname: edge1.platform.daf.gov.it
status: {}
