apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tba-nifi
  name: tba-nifi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tba-nifi
        nifi: "true"
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nexus.teamdigitale.test/tba-nifi.1.6.0:1.1.2-SNAPSHOT
        name: tba-nifi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8033
        - containerPort: 8082
        resources:
          limits:
            memory: 8384Mi
        volumeMounts:
        - name: glusterfsvol
          mountPath: /usr/nifi/data
          subPath: tba/evergreen2/nifi/data
          readOnly: false
        - name: glusterfsvol
          mountPath: /usr/nifi/logs
          subPath: tba/evergreen2/nifi/log
          readOnly: false
        - name: glusterfsvol
          mountPath: /tmp/kylo-nifi/failed-flows
          subPath: tba/evergreen2/nifi/failed-flows
          readOnly: false
        - name: glusterfsvol
          mountPath: /usr/nifi/extentions
          subPath: tba/evergreen2/nifi/extentions
          readOnly: false
        - name: sparkhome
          mountPath: /opt/cloudera/parcels/
          readOnly: true
        - name: sparkconf
          mountPath: /etc/spark2/
          readOnly: true
        - name: spark1conf
          mountPath: /etc/spark/
          readOnly: true
        - name: alternatives
          mountPath: /etc/alternatives/
          readOnly: true
        - name: glusterfsvol
          mountPath: /usr/nifi/daf.keytab
          subPath: tba/security/daf.keytab
          readOnly: true
        - name: glusterfsvol
          mountPath: /etc/security/
          subPath: tba/security/
          readOnly: true
        - name: nifi-config
          mountPath: /usr/nifi/conf
        - name: nifi-kylo
          mountPath: /usr/nifi/ext-config
        - name: hosts
          mountPath: /etc/extra_hosts
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
          readOnly: true
        - name: hadoop
          mountPath: /etc/hadoop
          readOnly: true
        - name: hive
          mountPath: /etc/hive
          readOnly: true
        - name: hbase
          mountPath: /etc/hbase
          readOnly: true
        - name: glusterfsvol
          mountPath: /usr/nifi/scripts
          subPath: nifi/scripts/edge1
          readOnly: true
        - name: home
          mountPath: /home
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: nifi-config
        configMap:
          name: nifi
      - name: nifi-kylo
        configMap:
          name: nifi-kylo
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoop
        hostPath:
          path: /etc/hadoop
      - name: sparkhome
        hostPath:
          path: /opt/cloudera/parcels/
      - name: alternatives
        hostPath:
          path: /etc/alternatives/
      - name: sparkconf
        hostPath:
          path: /etc/spark2/
      - name: spark1conf
        hostPath:
          path: /etc/spark/
      - name: hbase
        hostPath:
          path: /etc/hbase/
      - name: hive
        hostPath:
          path: /etc/hive/
      - name: home
        hostPath:
          path: /home
      nodeSelector:
        nifi: "true"
status: {}
