apiVersion: v1
data:
  kylo-spark-shell-starter.sh: |-
    kinit -k -t /etc/security/daf.keytab daf@DAF.GOV.IT
    /opt/cloudera/parcels/SPARK2/bin/spark-submit  --master  yarn  --conf  spark.driver.userClassPathFirst=true  --class com.thinkbiganalytics.spark.SparkShellApp  --driver-class-path /opt/kylo/kylo-services/lib:/opt/kylo/drivers/mariadb-java-client-1.5.7.jar /opt/kylo/kylo-services/lib/app/kylo-spark-shell-client-v2-0.9.1.jar --pgrep-marker=kylo-spark-shell-pgrep-mark &
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"kylo-spark-shell-starter.sh":"kinit -k -t /etc/security/daf.keytab daf@DAF.GOV.IT\n/opt/cloudera/parcels/CDH/bin/spark2-submit  --master  yarn  --conf  spark.driver.userClassPathFirst=true  --class  com.thinkbiganalytics.spark.SparkShellApp  --driver-class-path /opt/kylo/kylo-services/lib:/opt/kylo/drivers/mariadb-java-client-1.5.7.jar  --driver-java-options  -Dlog4j.configuration=/opt/kylo/kylo-services/conf/log4j-spark.properties  /opt/kylo/kylo-services/lib/app/kylo-spark-shell-client-v2-0.9.1.jar --pgrep-marker=kylo-spark-shell-pgrep-mark \u0026"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kylo-services-spark","namespace":"default"}}
  creationTimestamp: 2017-12-18T10:40:53Z
  name: kylo-services-spark
  namespace: default
  resourceVersion: "344609"
  selfLink: /api/v1/namespaces/default/configmaps/kylo-services-spark
  uid: ebf22d7d-e3df-11e7-b2e8-fa163e759c07