apiVersion: v1
kind: ConfigMap
metadata:
  name: kylo-ui
  namespace: default
data:
  log4j.properties: |-
    ###
    # #%L
    # thinkbig-ui-app
    # %%
    # Copyright (C) 2017 ThinkBig Analytics
    # %%
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #     http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # #L%
    ###
    # Root logger option
    log4j.rootLogger=INFO, file
    log4j.logger.com.thinkbiganalytics=INFO
    log4j.logger.org=WARN

    # Direct log messages to a log file
    log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.myAppender.DatePattern='.'yyyy-MM-dd
    log4j.appender.file.File=/var/log/kylo-ui/kylo-ui.log
    log4j.appender.file.append=true
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.Threshold=INFO
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %t:%c{1}:%L - %m%n
  application.properties: |-
    ###
    # #%L
    # thinkbig-ui-app
    # %%
    # Copyright (C) 2017 ThinkBig Analytics
    # %%
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #     http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # #L%
    ###
    ###
    # Other properties are in the ui-app/application.properties
    #

    #Default profile
    #spring.profiles.active=native,auth-kylo,auth-file
    spring.profiles.active=native,auth-kylo,auth-ldap


    ###
    # Authentication settings:
    #
    # Currently available athentication/authorization Spring profiles:
    #   *  auth-ldap   - authenticates users using LDAP and optionally loads any associated
    #                    user groups
    #   *  auth-ad     - authenticates users using Active Directory and loads any associated
    #                    user groups
    #   *  auth-simple - Uses authenticationService.username and authenticationService.password
    #                    for authentication (development only)
    #   *  auth-file   - Uses users.properties and roles.properties files for authentication
    #                    and role assignment (generally for development only)

    ## auth-file: If this profile is active then these optional properties may be used:

    security.auth.file.users=file:///opt/kylo/kylo-ui/conf/users.properties
    security.auth.file.groups=file:///opt/kylo/kylo-ui/conf/groups.properties
      #security.auth.file.password.hash.enabled=false
    #security.auth.file.password.hash.algorithm=MD5
    #security.auth.file.password.hash.encoding=base64

    ## auth-simple: If this profile is active these authenticationService properties are used:

    #authenticationService.username=dladmin
    #authenticationService.password={cipher}52fd39e4e4f7d0f6a91989efbfa870f1a543550401e6ab0b17f3059c1ada9b5f
    #authenticationService.password=thinkbig

    ## auth-ldap: If this profile is active then these properties should uncommented and updated appropriately

    security.auth.ldap.server.uri=ldap://idm.teamdigitale.test:389/cn=users,cn=accounts,dc=daf,dc=gov,dc=it
    security.auth.ldap.server.authDn=uid=application,cn=users,cn=accounts,dc=daf,dc=gov,dc=it
    security.auth.ldap.server.password=xxxxxx
    ### user DN patterns are separated by '|'
    security.auth.ldap.authenticator.userDnPatterns=uid={0}
    security.auth.ldap.user.enableGroups=false
    security.auth.ldap.user.groupNameAttr=member
    security.auth.ldap.user.groupsBase=cn=groups,cn=accounts,dc=daf,dc=gov,dc=it


    ## auth-ad: If this profile is active then these properties should uncommented and updated appropriately


    #security.auth.ad.server.uri=ldap://idm.teamdigitale.test
    #security.auth.ad.server.domain=cn=users,cn=accounts,dc=daf,dc=gov,dc=it
    ## These remaining properties are optional
    #security.auth.ad.user.enableGroups=true
    ## group attributes are separated by '|'
    #security.auth.ad.user.groupAttributes=


    #
    # Server port
    #
    server.port=8400
    server.ssl.enabled=false

    zuul.prefix=/proxy
    zuul.routes.api.path=/**
    zuul.routes.api.url=http://tba-kylo-services:8420/api
    ribbon.eureka.enabled=false
    zuul.debug.request=false
    ###Up the timeout so the UI doenst come back with Read Socket Timeout for longer running transactions
    zuul.host.socket-timeout-millis=3600000
    ##zuul.host.connect-timeout-millis

    ### allow large file uploads
    multipart.maxFileSize=-1
    multipart.maxRequestSize=-1

    # Login form authentication
    #security.jwt.algorithm=HS256
    security.jwt.key=<insert-256-bit-secret-key-here>
    security.rememberme.alwaysRemember=true
    #security.rememberme.cookieDomain=localhost
    #security.rememberme.cookieName=remember-me
    #security.rememberme.parameter=remember-me
    #security.rememberme.tokenValiditySeconds=1209600
    #security.rememberme.useSecureCookie=

    loginRestClientConfig.https=${server.ssl.enabled}
    loginRestClientConfig.host=tba-kylo-ui
    loginRestClientConfig.port=${server.port}
    loginRestClientConfig.path=${zuul.prefix}
    loginRestClientConfig.keystorePath=${server.ssl.key-store}
    loginRestClientConfig.keystorePassword=${server.ssl.key-store-password}
  application-context.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      #%L
      thinkbig-ui-app
      %%
      Copyright (C) 2017 ThinkBig Analytics
      %%
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
      #L%
      -->

    <beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:context="http://www.springframework.org/schema/context"
           xmlns="http://www.springframework.org/schema/beans"
           xsi:schemaLocation="http://www.springframework.org/schema/beans
                            http://www.springframework.org/schema/beans/spring-beans.xsd
                            http://www.springframework.org/schema/context
                            http://www.springframework.org/schema/context/spring-context.xsd">

      <bean id="applicationConfig" class="com.thinkbiganalytics.KyloUiApplication"/>

      <context:component-scan base-package="com.thinkbiganalytics">
        <context:exclude-filter type="assignable" expression="com.thinkbiganalytics.KyloUiApplication"/>
      </context:component-scan>

      <!-- Deprecate the use of the name component-context.xml in favor of plugin-context.xml.
          The latter more clearly states its purpose: how we identify and bootstrap a plugin's configuration.
          Leaving both in place for now. -->
      <import resource="classpath*:plugin/component-context.xml"/>
      <import resource="classpath*:plugin/plugin-context.xml"/>
      <import resource="classpath*:conf/*.xml"/>
      <import resource="classpath*:feed-manager/*.xml"/>

      <bean id="mainConfigurationClassPostProcessor" class="org.springframework.context.annotation.ConfigurationClassPostProcessor"/>
    </beans>
  users.properties: |-
      ###
      # #%L
      # thinkbig-security-auth-file
      # %%
      # Copyright (C) 2017 ThinkBig Analytics
      # %%
      # Licensed under the Apache License, Version 2.0 (the "License");
      # you may not use this file except in compliance with the License.
      # You may obtain a copy of the License at
      #
      #     http://www.apache.org/licenses/LICENSE-2.0
      #
      # Unless required by applicable law or agreed to in writing, software
      # distributed under the License is distributed on an "AS IS" BASIS,
      # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      # See the License for the specific language governing permissions and
      # limitations under the License.
      # #L%

      ###
      # These are the default users available when there is no explicit
      # users file provided in the configuration.
      #
      dladmin=thinkbig
      analyst=analyst
      designer=designer
      operator=operator
  groups.properties: |-
      ###
      # #%L
      # thinkbig-security-auth-file
      # %%
      # Copyright (C) 2017 ThinkBig Analytics
      # %%
      # Licensed under the Apache License, Version 2.0 (the "License");
      # you may not use this file except in compliance with the License.
      # You may obtain a copy of the License at
      #
      #     http://www.apache.org/licenses/LICENSE-2.0
      #
      # Unless required by applicable law or agreed to in writing, software
      # distributed under the License is distributed on an "AS IS" BASIS,
      # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      # See the License for the specific language governing permissions and
      # limitations under the License.
      # #L%

      ###
      # These are the default group assignments when there is no explicit
      # group file provided in the configuration.
      #
      dladmin=admin,user
      analyst=analyst,user
      designer=designer,user
      operator=operations,user
