apiVersion: v1
kind: Service
metadata:
  labels:
    app: tba-kylo-ui
  name: tba-kylo-ui
spec:
  type: "NodePort"
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
    nodePort: 31401
  selector:
    app: tba-kylo-ui
status:
  loadBalancer: {}